# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run webdriver tests

on:
  workflow_dispatch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    
    steps:
    # - name: Start selenoid
    #   uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v2
    - name: Switch to Node.js 12.21.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.21.0
    - name: Run tests
      run: npm cit  
    - name: Compress results
      uses: montudor/action-zip@v0.1.0
      if: ${{ always() }}
      with:
        args: zip -qq -r ./allure-results.zip ./allure-results
    - name: Send Results and Generate Report
      if: ${{ always() }}
      run: node --unhandled-rejections=strict ./scripts/upload-generate-report.js
    